# Generated by Django 5.2.6 on 2025-09-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Teacher",
        ),
    ]
